/// Flutter icons PronounceIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PronounceIcons
///      fonts:
///       - asset: fonts/PronounceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PronounceIcons {
  PronounceIcons._();

  static const _kFontFam = 'PronounceIcons';
  static const String? _kFontPkg = null;

  static const IconData clock_light = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_light = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_square_light = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_light = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_check_light = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_light = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_circle_light = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_square_light = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_square_light = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle_light = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_light = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt_lines_light = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_light = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_right_light = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_light = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_light = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_alt_right_light = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right_light = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones_light = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_light = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_square_light = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wave_triangle_light = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_light = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waveform_path_light = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waveform_light = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_light = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs_light = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_light = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt_light = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_light = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_light = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass_light = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket_launch_light = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planet_ringed_light = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_light = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_light = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_left_light = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left_light = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_light = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_light = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_alt_left_light = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_left_light = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone_light = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_light = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData books_light = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
